blank_issues_enabled: false
contact_links:
  - name: "💡 Suggest a feature"
    url: https://github.com/Zoybean/majjic/discussions
    about: Start a discussion suggest an improvement or a new feature.
  - name: "🆘 Ask the Majjic maintainers for support"
    url: https://github.com/Zoybean/majjic/discussions
    about: Please keep in mind that our bandwidth is limited.
  - name: "ℹ️ Magit FAQ"
    url: https://magit.vc/manual/magit/FAQ.html
    about: Magit users might have had the same question before.
  - name: "ℹ️ Magit Manual"
    url: https://magit.vc/manual/magit/#Top
    about: The Magit manual may also be of use.
